name: CI

on: [push]


jobs:

  format-test-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Version
        run: cargo --version;rustc --version

      - name: Check formatting
        run: cargo fmt --check --verbose

      - name: Build solution
        run: cargo build --verbose

      - name: Run Tests
        run: cargo test --verbose




